### ISSUE TITLE
Schachinteraktion: nicht/schwer bedienbar

### ISSUE THREAD

**Issue by smeerws** [4ahmns2122-VR/VRProjekt2122-seliskases#10]
Schach-Interaktion verhält sich unlogisch, Vermutung Koordinatensysteme Konvertierung passt nicht

https://user-images.githubusercontent.com/28704310/151799007-8bb99c7f-f75d-4c4c-a3d6-522c41b2da23.mp4

**Comment by simoneliskases** [comment]
Fixed.

Reasons: 
- Error in Pawn Movement Algorithm
- Switched Inputs
- Problem with OnSelect Event
