### ISSUE TITLE
Readme limitations update

### ISSUE THREAD

**Issue by smeerws** [4ahmns2122-VR/VRProjekt2122-seliskases#4]
Takeaway sollte hier sein, dass auch andere das Problem nachvollziehen können.
1) Beschreibung Abweichung geplante Umsetzung zum aktuellen Stand.
2) Was genau war das Problem, und was wurde zur Lösung versucht.

#Limitations
- Gameplay/UI Problem 1: #3

**Comment by simoneliskases** [comment]
Updated Readme
