### ISSUE TITLE
Bild mit Chess hat sich zu drehen begonnen

### ISSUE THREAD

**Issue by smeerws** [4ahmns2122-VR/VRProjekt2122-seliskases#8]
Hatte gebrauch zu verstehen, dass ich den btn mit der hand für restart drücken muss, dann ist irgendwas passiert und der bilderrahmen mit dem schach hat sich zu drehen begonnen

**Comment by simoneliskases** [comment]
Fixed.
The Rigidbody of the chessboard interacted with the rigid body of the key. Solved by setting the chessboard's rigidbody to kinematic.
