### ISSUE TITLE
Schachfigur schmelzen erst nach ankommen in der Experience

### ISSUE THREAD

**Issue by smeerws** [4ahmns2122-VR/VRProjekt2122-seliskases#9]
Das mit der schmelzenden Figur kommt jetzt noch nicht so raus, ich würde erst mal den Spieler ankommen lassen und dann erst mit dem Schmelzen beginnen. Es dauert immer bis man die Brille aufhat etc. sonst geht das unter

**Comment by simoneliskases** [comment]
Fixed: Added Delay
